//
// Created by dongmin on 18. 3. 23.
//

#ifndef TRIANGLEMESHTOCLEARSOLID_COLLADAIMPORTER_H
#define TRIANGLEMESHTOCLEARSOLID_COLLADAIMPORTER_H


class COLLADAImporter {

};


#endif //TRIANGLEMESHTOCLEARSOLID_COLLADAIMPORTER_H
